name: Auto Push

on:
  schedule:
    - cron: '0 1,8
    ,14,20 * * *'  # Har kuni 01:00, 09:00, 14:00 va 20:00 da ishga tushadi
  workflow_dispatch:  # Qo'lda ishga tushirish imkoniyati

jobs:
  auto-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repositoryni yuklab olish
        uses: actions/checkout@v3

      - name: Yangi o'zgarish kiritish
        run: |
          echo "Yangi o'zgarish: $(date)" >> log.txt

      - name: Git konfiguratsiyasi
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: O'zgarishlarni commit qilish
        run: |
          git add .
          git commit -m "Avtomatik commit: $(date)" || echo "Hech qanday o'zgarish yo'q"

      - name: Push qilish
        run: |
          git remote set-url origin https://x-access-token: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@github.com/MuhammadKarimov-dev/Portfolio.git
          git push origin main
